### PR TITLE
Create Plugin: Fix failing scaffolds due to marked

### LINKED ISSUE #1318: something did not work in @grafana/create-plugin@latest(5.9 I believe)
I tried to run that command and it gave me error message

✔ Select a plugin type · panel
✔ Enter a name for your plugin · safas
✔ Enter your organization name (usually your Grafana Cloud org) · xxx

✔︎ Scaffolded xxx-asfa-panel panel plugin 
✔︎ Added basic E2E test (Playwright)
✔︎ Set up provisioning for basic dashboard and TestData data source instance
✔︎ Configured development environment (Docker)
✔︎ Added default GitHub actions for CI, releases and Grafana compatibility

file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:474
  return text.replace(/:([A-Za-z0-9_\-\+]+?):/g, function (emojiString) {
              ^

TypeError: text.replace is not a function
Please report this to https://github.com/markedjs/marked.
    at Renderer.insertEmojis [as emoji] (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:474:15)
    at Renderer.transform (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:529:24)
    at Renderer.heading (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:96:15)
    at extension.renderer.<computed> (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:264:23)
    at renderer.<computed> [as heading] (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:2261:48)
    at _Parser.parse (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:1947:42)
    at parse (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:1911:23)
    at Marked.parse (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:2405:28)
    at marked (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:2439:27)
    at displayAsMarkdown (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/dist/utils/utils.console.js:11:12)

Node.js v20.14.0

I then tried to npx @grafana/create-plugin@5.8.0, which worked. 

% npx @grafana/create-plugin@5.8.0 
Need to install the following packages:
@grafana/create-plugin@5.8.0
Ok to proceed? (y) y

✔ Select a plugin type · panel
✔ Enter a name for your plugin · tst
✔ Enter your organization name (usually your Grafana Cloud org) · lhj

✔︎ Scaffolded lhj-tst-panel panel plugin 
✔︎ Added basic E2E test (Playwright)
✔︎ Set up provisioning for basic dashboard and TestData data source instance
✔︎ Configured development environment (Docker)
✔︎ Added default GitHub actions for CI, releases and Grafana compatibility

# Congratulations on scaffolding a Grafana panel plugin! 🚀

## What's next?

Run the following commands to get started:

    * cd ./lhj-tst-panel
    * npm install to install frontend dependencies.
    * npm exec playwright install chromium to install e2e test dependencies.
    * npm run dev to build (and watch) the plugin frontend code.
    * docker compose up to start a grafana development server.
    * Open http://localhost:3000 in your browser to create a dashboard to begin developing your plugin.

Note: We strongly recommend creating a new Git repository by running git init in ./lhj-tst-panel before continuing.

    * Learn more about Grafana Plugin Development at https://grafana.com/developers/plugin-tools

so I think there might be something wrong with the latest patch?

### PR DESCRIPTION
**Pull request by jackw**
**What this PR does / why we need it**:
Marked terminal and marked dependencies on npx runs are resolved incorrectly and cause scaffolding to fail to succeed.

**Before**

```
npx -y @grafana/create-plugin@latest
✔ Select a plugin type · panel
✔ Enter a name for your plugin · safas
✔ Enter your organization name (usually your Grafana Cloud org) · xxx
file:///Users/jackwestbrook/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:474
  return text.replace(/:([A-Za-z0-9_\-\+]+?):/g, function (emojiString) {
              ^

TypeError: text.replace is not a function
Please report this to https://github.com/markedjs/marked.
    at insertEmojis (file:///Users/jackwestbrook/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:474:15)
    at file:///Users/jackwestbrook/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:529:24
    at file:///Users/jackwestbrook/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:529:24
    at Renderer.paragraph (file:///Users/jackwestbrook/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:134:10)
    at extension.renderer.<computed> (file:///Users/jackwestbrook/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:264:23)
    at renderer.<computed> [as paragraph] (file:///Users/jackwestbrook/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:2261:48)
    at _Parser.parse (file:///Users/jackwestbrook/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:1971:42)
    at parse (file:///Users/jackwestbrook/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:1911:23)
    at Marked.parse (file:///Users/jackwestbrook/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:2405:28)
    at marked (file:///Users/jackwestbrook/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:2439:27)

Node.js v20.16.0
```

**After**

```
npx -y  @grafana/create-plugin@5.9.1-canary.1319.459d73f.0
✔ Select a plugin type · panel
✔ Enter a name for your plugin · safas
✔ Enter your organization name (usually your Grafana Cloud org) · xxx

✔︎ Scaffolded xxx-safas-panel panel plugin
✔︎ Added basic E2E test (Playwright)
✔︎ Set up provisioning for basic dashboard and TestData data source instance
✔︎ Configured development environment (Docker)
✔︎ Added default GitHub actions for CI, releases and Grafana compatibility


# Congratulations on scaffolding a Grafana panel plugin! 🚀

## What's next?

Run the following commands to get started:

    * `cd ./xxx-safas-panel`
    * `npm install` to install frontend dependencies.
    * `npm exec playwright install chromium` to install e2e test dependencies.
    * `npm run dev` to build (and watch) the plugin frontend code.
    * `docker compose up` to start a grafana development server.
    * Open http://localhost:3000 in your browser to create a dashboard to begin developing your plugin.

Note: We strongly recommend creating a new Git repository by running git init in ./xxx-safas-panel before continuing.

    * Learn more about Grafana Plugin Development at https://grafana.com/developers/plugin-tools

```

**Which issue(s) this PR fixes**:

Fixes #1318

**Special notes for your reviewer**:

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @grafana/create-plugin@5.9.1-canary.1319.459d73f.0
  # or 
  yarn add @grafana/create-plugin@5.9.1-canary.1319.459d73f.0
  ```
</details>

### CODE REVIEW

File: package-lock.json [hunk 1]
```diff
@@ -31366,6 +31367,10 @@
       },
       "devDependencies": {
         "@types/glob": "^8.0.0",
+        "@types/marked-terminal": "^6.0.1",
+        "@types/minimist": "^1.2.2",
+        "@types/semver": "^7.3.9",
+        "@types/which": "^3.0.0",
```
Comment (jackw) [inline package-lock.json:31373]: We don't ship TS types with this package so there's no need for these to be dependencies. `@types/marked-terminal` has a peer dependency on marked which was also causing limitations in the versions of marked installed via `npx`.

**Review by sunker — APPROVED** [review]
🚀
