### ISSUE TITLE
something did not work in @grafana/create-plugin@latest(5.9 I believe)

### ISSUE THREAD

**Issue by morpinma-wing** [grafana/plugin-tools#1318]
I tried to run that command and it gave me error message

✔ Select a plugin type · panel
✔ Enter a name for your plugin · safas
✔ Enter your organization name (usually your Grafana Cloud org) · xxx

✔︎ Scaffolded xxx-asfa-panel panel plugin 
✔︎ Added basic E2E test (Playwright)
✔︎ Set up provisioning for basic dashboard and TestData data source instance
✔︎ Configured development environment (Docker)
✔︎ Added default GitHub actions for CI, releases and Grafana compatibility

file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:474
  return text.replace(/:([A-Za-z0-9_\-\+]+?):/g, function (emojiString) {
              ^

TypeError: text.replace is not a function
Please report this to https://github.com/markedjs/marked.
    at Renderer.insertEmojis [as emoji] (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:474:15)
    at Renderer.transform (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:529:24)
    at Renderer.heading (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:96:15)
    at extension.renderer.<computed> (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/marked-terminal/index.js:264:23)
    at renderer.<computed> [as heading] (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:2261:48)
    at _Parser.parse (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:1947:42)
    at parse (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:1911:23)
    at Marked.parse (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:2405:28)
    at marked (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/node_modules/marked/lib/marked.esm.js:2439:27)
    at displayAsMarkdown (file:///Users/xxx/.npm/_npx/c8ca622b04c0c218/node_modules/@grafana/create-plugin/dist/utils/utils.console.js:11:12)

Node.js v20.14.0

I then tried to npx @grafana/create-plugin@5.8.0, which worked. 

% npx @grafana/create-plugin@5.8.0 
Need to install the following packages:
@grafana/create-plugin@5.8.0
Ok to proceed? (y) y

✔ Select a plugin type · panel
✔ Enter a name for your plugin · tst
✔ Enter your organization name (usually your Grafana Cloud org) · lhj

✔︎ Scaffolded lhj-tst-panel panel plugin 
✔︎ Added basic E2E test (Playwright)
✔︎ Set up provisioning for basic dashboard and TestData data source instance
✔︎ Configured development environment (Docker)
✔︎ Added default GitHub actions for CI, releases and Grafana compatibility

# Congratulations on scaffolding a Grafana panel plugin! 🚀

## What's next?

Run the following commands to get started:

    * cd ./lhj-tst-panel
    * npm install to install frontend dependencies.
    * npm exec playwright install chromium to install e2e test dependencies.
    * npm run dev to build (and watch) the plugin frontend code.
    * docker compose up to start a grafana development server.
    * Open http://localhost:3000 in your browser to create a dashboard to begin developing your plugin.

Note: We strongly recommend creating a new Git repository by running git init in ./lhj-tst-panel before continuing.

    * Learn more about Grafana Plugin Development at https://grafana.com/developers/plugin-tools

so I think there might be something wrong with the latest patch?

**Comment by jackw** [comment]
@morpinma-wing Many thanks for raising this issue. May I ask in future if you find a bug to please report it using our [bug issue template](https://github.com/grafana/plugin-tools/issues/new?template=bug_report.yml) which gathers all the information we require up front.

I've managed to reproduce the issue and I've opened #1319 which should fix things.
