### ISSUE TITLE
Bug: Recent PR to update create-plugin config broke webpack

### ISSUE THREAD

**Issue by cap10morgan** [grafana/plugin-tools#1464]
### Which package(s) does this bug affect?

- [x] Create Plugin
- [ ] Sign Plugin
- [ ] Plugin E2E
- [ ] Plugin Meta Extractor

### Package versions

```shell
That command reports 5.13.0 but the PR upgraded the config from 5.11.1 to 5.12.4
```

### What happened?

GitHub Actions opened this PR: https://github.com/HarperDB/grafana-datasource/pull/2

After merging it, I get this error when running `npm run dev`:

```
[webpack-cli] Failed to load '/Users/wes/dev/grafana-datasource/.config/webpack/webpack.config.ts' config
[webpack-cli] Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/wes/dev/grafana-datasource/.config/webpack/BuildModeWebpackPlugin' imported from /Users/wes/dev/grafana-datasource/.config/webpack/webpack.config.ts
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:716:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:640:25)
    at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:675:38)
    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:698:52)
    at #cachedResolveSync (node:internal/modules/esm/loader:659:25)
    at ModuleLoader.getModuleJobForRequire (node:internal/modules/esm/loader:387:50)
    at new ModuleJobSync (node:internal/modules/esm/module_job:342:34) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/wes/dev/grafana-datasource/.config/webpack/BuildModeWebpackPlugin'
}
```

### What you expected to happen

`npm run dev` to build and watch my frontend code like it had been doing before the upgrade PR

### How to reproduce it (as minimally and precisely as possible)

Not really sure. The PR diff maybe gives enough info?

### Environment

```shell
System:
    OS: macOS 15.2
    CPU: (12) arm64 Apple M3 Pro
    Memory: 88.81 MB / 18.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 23.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 132.0.6834.84
    Safari: 18.2
  npmPackages:
    @grafana/data: ^11.3.2 => 11.4.0 
    @grafana/eslint-config: ^8.0.0 => 8.0.0 
    @grafana/plugin-e2e: ^1.13.1 => 1.14.7 
    @grafana/runtime: ^11.3.2 => 11.4.0 
    @grafana/schema: ^11.3.2 => 11.4.0 
    @grafana/tsconfig: ^2.0.0 => 2.0.0 
    @grafana/ui: ^11.3.2 => 11.4.0
```

### Additional context

I reviewed the changes in the PR and they seemed fine.

Here's the contents of my `.config/webpack/webpack.config.ts` file:

```typescript
/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/create-plugin`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.com/developers/plugin-tools/get-started/set-up-development-environment#extend-the-webpack-config
 */

import CopyWebpackPlugin from 'copy-webpack-plugin';
import ESLintPlugin from 'eslint-webpack-plugin';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
import path from 'path';
import ReplaceInFileWebpackPlugin from 'replace-in-file-webpack-plugin';
import TerserPlugin from 'terser-webpack-plugin';
import { SubresourceIntegrityPlugin } from 'webpack-subresource-integrity';
import { type Configuration, BannerPlugin } from 'webpack';
import LiveReloadPlugin from 'webpack-livereload-plugin';
import VirtualModulesPlugin from 'webpack-virtual-modules';

import { BuildModeWebpackPlugin } from './BuildModeWebpackPlugin';
import { DIST_DIR, SOURCE_DIR } from './constants';
import { getCPConfigVersion, getEntries, getPackageJson, getPluginJson, hasReadme, isWSL } from './utils';

const pluginJson = getPluginJson();
const cpVersion = getCPConfigVersion();

const virtualPublicPath = new VirtualModulesPlugin({
  'node_modules/grafana-public-path.js': `
import amdMetaModule from 'amd-module';

__webpack_public_path__ =
  amdMetaModule && amdMetaModule.uri
    ? amdMetaModule.uri.slice(0, amdMetaModule.uri.lastIndexOf('/') + 1)
    : 'public/plugins/${pluginJson.id}/';
`,
});

const config = async (env): Promise<Configuration> => {
  const baseConfig: Configuration = {
    cache: {
      type: 'filesystem',
      buildDependencies: {
        config: [__filename],
      },
    },

    context: path.join(process.cwd(), SOURCE_DIR),

    devtool: env.production ? 'source-map' : 'eval-source-map',

    entry: await getEntries(),

    externals: [
      // Required for dynamic publicPath resolution
      { 'amd-module': 'module' },
      'lodash',
      'jquery',
      'moment',
      'slate',
      'emotion',
      '@emotion/react',
      '@emotion/css',
      'prismjs',
      'slate-plain-serializer',
      '@grafana/slate-react',
      'react',
      'react-dom',
      'react-redux',
      'redux',
      'rxjs',
      'react-router',
      'react-router-dom',
      'd3',
      'angular',
      '@grafana/ui',
      '@grafana/runtime',
      '@grafana/data',

      // Mark legacy SDK imports as external if their name starts with the "grafana/" prefix
      ({ request }, callback) => {
        const prefix = 'grafana/';
        const hasPrefix = (request) => request.indexOf(prefix) === 0;
        const stripPrefix = (request) => request.substr(prefix.length);

        if (hasPrefix(request)) {
          return callback(undefined, stripPrefix(request));
        }

        callback();
      },
    ],

    // Support WebAssembly according to latest spec - makes WebAssembly module async
    experiments: {
      asyncWebAssembly: true,
    },

    mode: env.production ? 'production' : 'development',

    module: {
      rules: [
        // This must come first in the rules array otherwise it breaks sourcemaps.
        {
          test: /src\/(?:.*\/)?module\.tsx?$/,
          use: [
            {
              loader: 'imports-loader',
              options: {
                imports: `side-effects grafana-public-path`,
              },
            },
          ],
        },
        {
          exclude: /(node_modules)/,
          test: /\.[tj]sx?$/,
          use: {
            loader: 'swc-loader',
            options: {
              jsc: {
                baseUrl: path.resolve(process.cwd(), SOURCE_DIR),
                target: 'es2015',
                loose: false,
                parser: {
                  syntax: 'typescript',
                  tsx: true,
                  decorators: false,
                  dynamicImport: true,
                },
              },
            },
          },
        },
        {
          test: /\.css$/,
          use: ['style-loader', 'css-loader'],
        },
        {
          test: /\.s[ac]ss$/,
          use: ['style-loader', 'css-loader', 'sass-loader'],
        },
        {
          test: /\.(png|jpe?g|gif|svg)$/,
          type: 'asset/resource',
          generator: {
            filename: Boolean(env.production) ? '[hash][ext]' : '[file]',
          },
        },
        {
          test: /\.(woff|woff2|eot|ttf|otf)(\?v=\d+\.\d+\.\d+)?$/,
          type: 'asset/resource',
          generator: {
            filename: Boolean(env.production) ? '[hash][ext]' : '[file]',
          },
        },
      ],
    },

    optimization: {
      minimize: Boolean(env.production),
      minimizer: [
        new TerserPlugin({
          terserOptions: {
            format: {
              comments: (_, { type, value }) => type === 'comment2' && value.trim().startsWith('[create-plugin]'),
            },
            compress: {
              drop_console: ['log', 'info'],
            },
          },
        }),
      ],
    },

    output: {
      clean: {
        keep: new RegExp(`(.*?_(amd64|arm(64)?)(.exe)?|go_plugin_build_manifest)`),
      },
      filename: '[name].js',
      chunkFilename: env.production ? '[name].js?_cache=[contenthash]' : '[name].js',
      library: {
        type: 'amd',
      },
      path: path.resolve(process.cwd(), DIST_DIR),
      publicPath: `public/plugins/${pluginJson.id}/`,
      uniqueName: pluginJson.id,
      crossOriginLoading: 'anonymous',
    },

    plugins: [
      new BuildModeWebpackPlugin(),
      virtualPublicPath,
      // Insert create plugin version information into the bundle
      new BannerPlugin({
        banner: '/* [create-plugin] version: ' + cpVersion + ' */',
        raw: true,
        entryOnly: true,
      }),
      new CopyWebpackPlugin({
        patterns: [
          // If src/README.md exists use it; otherwise the root README
          // To `compiler.options.output`
          { from: hasReadme() ? 'README.md' : '../README.md', to: '.', force: true },
          { from: 'plugin.json', to: '.' },
          { from: '../LICENSE', to: '.' },
          { from: '../CHANGELOG.md', to: '.', force: true },
          { from: '**/*.json', to: '.' },
          { from: '**/*.svg', to: '.', noErrorOnMissing: true },
          { from: '**/*.png', to: '.', noErrorOnMissing: true },
          { from: '**/*.html', to: '.', noErrorOnMissing: true },
          { from: 'img/**/*', to: '.', noErrorOnMissing: true },
          { from: 'libs/**/*', to: '.', noErrorOnMissing: true },
          { from: 'static/**/*', to: '.', noErrorOnMissing: true },
          { from: '**/query_help.md', to: '.', noErrorOnMissing: true },
        ],
      }),
      // Replace certain template-variables in the README and plugin.json
      new ReplaceInFileWebpackPlugin([
        {
          dir: DIST_DIR,
          files: ['plugin.json', 'README.md'],
          rules: [
            {
              search: /\%VERSION\%/g,
              replace: getPackageJson().version,
            },
            {
              search: /\%TODAY\%/g,
              replace: new Date().toISOString().substring(0, 10),
            },
            {
              search: /\%PLUGIN_ID\%/g,
              replace: pluginJson.id,
            },
          ],
        },
      ]),
      new SubresourceIntegrityPlugin({
        hashFuncNames: ['sha256'],
      }),
      ...(env.development
        ? [
            new LiveReloadPlugin(),
            new ForkTsCheckerWebpackPlugin({
              async: Boolean(env.development),
              issue: {
                include: [{ file: '**/*.{ts,tsx}' }],
              },
              typescript: { configFile: path.join(process.cwd(), 'tsconfig.json') },
            }),
            new ESLintPlugin({
              extensions: ['.ts', '.tsx'],
              lintDirtyModulesOnly: Boolean(env.development), // don't lint on start, only lint changed files
            }),
          ]
        : []),
    ],

    resolve: {
      extensions: ['.js', '.jsx', '.ts', '.tsx'],
      // handle resolving "rootDir" paths
      modules: [path.resolve(process.cwd(), 'src'), 'node_modules'],
      unsafeCache: true,
    },
  };

  if (isWSL()) {
    baseConfig.watchOptions = {
      poll: 3000,
      ignored: /node_modules/,
    };
  }

  return baseConfig;
};

export default config;
```

The file `.config/webpack/BuildModeWebpackPlugin.ts` exists and has the following contents:

```typescript
import * as webpack from 'webpack';

const PLUGIN_NAME = 'BuildModeWebpack';

export class BuildModeWebpackPlugin {
  apply(compiler: webpack.Compiler) {
    compiler.hooks.compilation.tap(PLUGIN_NAME, (compilation) => {
      compilation.hooks.processAssets.tap(
        {
          name: PLUGIN_NAME,
          stage: webpack.Compilation.PROCESS_ASSETS_STAGE_ADDITIONS,
        },
        async () => {
          const assets = compilation.getAssets();
          for (const asset of assets) {
            if (asset.name.endsWith('plugin.json')) {
              const pluginJsonString = asset.source.source().toString();
              const pluginJsonWithBuildMode = JSON.stringify(
                {
                  ...JSON.parse(pluginJsonString),
                  buildMode: compilation.options.mode,
                },
                null,
                4
              );
              compilation.updateAsset(asset.name, new webpack.sources.RawSource(pluginJsonWithBuildMode));
            }
          }
        }
      );
    });
  }
}
```

**Comment by cap10morgan** [comment]
I ran `npx @grafana/create-plugin update` in my plugin working directory and got bumped to 5.13.0. But that has the same error when I run `npm run dev`

**Comment by leventebalogh** [comment]
Hey @cap10morgan 👋 

Thanks a lot for reaching out! Hmm, based on the error it looks it's simply not finding the `BuildModeWebpackPlugin` module, which is weird, [it was added in `5.8.0`](https://github.com/grafana/plugin-tools/pull/1281#issuecomment-2451514698) and when I was trying to reproduce it locally it was always there (I tried scaffolding a plugin with 5.7.0 and then updating in different ways). 

Unfortunately I cannot see the PR due to permissions, could you by any chance give access to me or the plugins platform team? Can you please validate that the PR didn't delete the `BuildModeWebpackPlugin.ts` file?

As a quickfix you could try adding the following file to your project and see if it fixes the issue:

**Path:** `<project-root>/.config/webpack/BuildModeWebpackPlugin.ts`
**Content:**
```ts
import * as webpack from 'webpack';

const PLUGIN_NAME = 'BuildModeWebpack';

export class BuildModeWebpackPlugin {
  apply(compiler: webpack.Compiler) {
    compiler.hooks.compilation.tap(PLUGIN_NAME, (compilation) => {
      compilation.hooks.processAssets.tap(
        {
          name: PLUGIN_NAME,
          stage: webpack.Compilation.PROCESS_ASSETS_STAGE_ADDITIONS,
        },
        async () => {
          const assets = compilation.getAssets();
          for (const asset of assets) {
            if (asset.name.endsWith('plugin.json')) {
              const pluginJsonString = asset.source.source().toString();
              const pluginJsonWithBuildMode = JSON.stringify(
                {
                  ...JSON.parse(pluginJsonString),
                  buildMode: compilation.options.mode,
                },
                null,
                4
              );
              compilation.updateAsset(asset.name, new webpack.sources.RawSource(pluginJsonWithBuildMode));
            }
          }
        }
      );
    });
  }
}

```

**Comment by cap10morgan** [comment]
@leventebalogh Thanks! Yeah, happy to give you and whoever else on your team access to the repo in question. What is the team handle to add?

**Comment by cap10morgan** [comment]
@leventebalogh Actually I checked w/ the higher-ups and they confirmed it was OK to open source that repo. So you and everyone else should be able to see that PR now. Thanks again!

**Comment by jackw** [comment]
@cap10morgan I've cloned the repo and I cannot reproduce the issue you've reported having with local development.

```
$ gh repo clone HarperDB/grafana-datasource
Cloning into 'grafana-datasource'...
remote: Enumerating objects: 223, done.
remote: Counting objects: 100% (223/223), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 223 (delta 100), reused 212 (delta 92), pack-reused 0 (from 0)
Receiving objects: 100% (223/223), 275.52 KiB | 1000.00 KiB/s, done.
Resolving deltas: 100% (100/100), done.

$ cd grafana-datasource
$ ls
CHANGELOG.md         Magefile.go          docker-compose.yaml  go.sum               jest-setup.js        package-lock.json    pkg                  provisioning         tests
LICENSE              README.md            go.mod               hdb                  jest.config.js       package.json         playwright.config.ts src                  tsconfig.json

$ npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm warn deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 1193 packages, and audited 1194 packages in 6s

203 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npm run build

> harperdb-datasource@1.0.0 build
> webpack -c ./.config/webpack/webpack.config.ts --env production

assets by path *.md 2.58 KiB
  asset README.md 2.53 KiB [emitted] [from: README.md] [copied]
  asset CHANGELOG.md 53 bytes [emitted] [from: ../CHANGELOG.md] [copied]
asset img/logo.svg 22.5 KiB [emitted] [from: img/logo.svg] [copied]
asset module.js 13.4 KiB [emitted] [minimized] (name: module) 1 related asset
asset LICENSE 11.1 KiB [emitted] [from: ../LICENSE] [copied]
asset plugin.json 832 bytes [emitted] [from: plugin.json] [copied]
runtime modules 999 bytes 6 modules
orphan modules 29 KiB [orphan] 5 modules
built modules 29.6 KiB [built]
  modules by path external "@grafana/ 126 bytes
    external "@grafana/data" 42 bytes [built] [code generated]
    external "@grafana/runtime" 42 bytes [built] [code generated]
    external "@grafana/ui" 42 bytes [built] [code generated]
  ./module.ts + 5 modules 29.4 KiB [built] [code generated]
  external "module" 42 bytes [built] [code generated]
  external "react" 42 bytes [built] [code generated]
webpack 5.97.1 compiled successfully in 353 ms

$ npm run dev

> harperdb-datasource@1.0.0 dev
> webpack -w -c ./.config/webpack/webpack.config.ts --env development

<i> [LiveReloadPlugin] Live Reload listening on port 35729
assets by status 36.2 KiB [compared for emit]
  assets by path *.md 2.58 KiB
    asset README.md 2.53 KiB [compared for emit] [from: README.md] [copied]
    asset CHANGELOG.md 53 bytes [compared for emit] [from: ../CHANGELOG.md] [copied]
  asset img/logo.svg 22.5 KiB [compared for emit] [from: img/logo.svg] [copied]
  asset LICENSE 11.1 KiB [compared for emit] [from: ../LICENSE] [copied]
assets by status 91.8 KiB [emitted]
  asset module.js 91 KiB [emitted] (name: module)
  asset plugin.json 833 bytes [emitted] [from: plugin.json] [copied]
runtime modules 999 bytes 5 modules
built modules 29.6 KiB [built]
  cacheable modules 29.4 KiB
    modules by path ./*.ts 6.16 KiB 3 modules
    modules by path ./components/*.tsx 23 KiB
      ./components/ConfigEditor.tsx 4.7 KiB [built] [code generated]
      ./components/QueryEditor.tsx 18.4 KiB [built] [code generated]
    ./node_modules/grafana-public-path.js 223 bytes [built] [code generated]
  modules by path external "@grafana/ 126 bytes
    external "@grafana/data" 42 bytes [built] [code generated]
    external "@grafana/runtime" 42 bytes [built] [code generated]
    external "@grafana/ui" 42 bytes [built] [code generated]
  external "module" 42 bytes [built] [code generated]
  external "react" 42 bytes [built] [code generated]
webpack 5.97.1 compiled successfully in 205 ms
Type-checking in progress...
assets by status 127 KiB [cached] 5 assets
asset plugin.json 833 bytes [emitted] [from: plugin.json] [copied]
cached modules 29.6 KiB (javascript) 999 bytes (runtime) [cached] 16 modules
webpack 5.97.1 compiled successfully in 87 ms
Type-checking in progress...
No errors found.
```

I also see failures your CI. I believe they're caused by the package-lock.json change in [this PR](https://github.com/HarperDB/grafana-datasource/pull/3). Something has deleted all the swc/core bindings except the one for Mac Silicon. 

Please try running `npm i -D @swc/core@1.10.7` locally to put back the missing rust bindings. Pushing that to a gh branch should kick off the CI again and 🤞 it will solve that issue.

**Comment by cap10morgan** [comment]
@jackw OK, thanks! Yeah, that did fix the CI issue. 👍🏻 

And I am getting the same error when I clone a fresh working copy of this, so it must be something in my environment. What versions of node and npm were you using? I'm on npm 10.9.2 and node 23.6.0.

I'll try it on another machine and see if I can reproduce it.

**Comment by cap10morgan** [comment]
Ah ha! I installed Node 22.13.1 on the same machine where this was failing and that fixed it. So this is apparently a bug with Node 23.6.0.

**Comment by cap10morgan** [comment]
The error still occurs with Node 23.6.1

**Comment by leventebalogh** [comment]
Hmm, thanks @cap10morgan, we will have a look 👍

**Comment by jackw** [comment]
> So this is apparently a bug with Node 23.6.0.
> The error still occurs with Node 23.6.1

This is due to node 23.6 unflagging typescript compilation support by default ([info here](https://nodejs.org/en/blog/release/v23.6.0#unflagging---experimental-strip-types)). If you install node 23.5 this problem should go away. We really appreciate your help in figuring out this issue and we will put effort into fixing this in time for the Node 24 LTS release in Oct of this year.

As we only [support LTS](https://grafana.com/developers/plugin-tools/#recommended-tooling) versions of node I'm going to go ahead and close this issue and I would suggest you downgrade to node 22 for the time being as @leventebalogh suggested.
